name: Run go tests on master branch
run-name: Run go tests on master branch

on:
  pull_request:
    branches: [ "master" ]

jobs: 
  golang-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Run go test
        run: go test -v .