apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: uniwise
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: '18.3.2'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: uniwise
      interval: 1m